### PR TITLE
Add kinesis firehose as a resource.

### PR DESCRIPTION
**Pull request by chwevans**

### CODE REVIEW

**Comment by grahamjenson** [comment]
+1

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1 | Message
------------ | ------------- | ----------
grahamjenson | 1 | +1 



[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/geoengineer&ref=76ded6cd665c9ddd5a7139e3e5b96e5f7fdf20fe)

**Comment by grahamjenson** [comment]
+1

**Comment by heimdall-asguard** [comment]
This Pull Request was merged without enough reviews
Please go [here](https://github.com/coinbase/geoengineer/issues/180) to review and +1

**Pull request merged**
