### PR TITLE
Add a --yes option to apply to ignore interactivity.

### PR DESCRIPTION
**Pull request by chwevans**

### CODE REVIEW

**Comment by heimdall-asguard** [comment]
Reviews      | 0/1 | Message
------------ | ------------- | ----------




[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/geoengineer&ref=5942ed47f45baa2e7d6a9bb1fe7fb46283c19ec2)

**Comment by niallo** [comment]
+1

**Comment by heimdall-asguard** [comment]
Review Error for niallo@2018-06-24T03:53:47+00:00
User must have write permissions to review

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1 | Message
------------ | ------------- | ----------
krobertson | 1 | approved 

Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/geoengineer&ref=e09518444641932c07cbcfc7e56b5bfb693545fc)

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1 | Message
------------ | ------------- | ----------
krobertson | 1 | approved 

Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/geoengineer&ref=eda43fc1b6babc462083c124e12e5c70b12f7db4)

**Pull request merged**
