### PR TITLE
[Fix] Readme

### PR DESCRIPTION
**Pull request by grahamjenson**

### CODE REVIEW

**Comment by heimdall-asguard** [comment]
Reviews      | 0/1 | Message
------------ | ------------- | ----------




[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/geoengineer&ref=5b8b0dd4fc547543f1d667e8fbafae749b2fb545)

**Comment by grahamjenson** [comment]
+1

**Comment by heimdall-asguard** [comment]
User cannot review their own pull request

**Comment by brad-larson** [comment]
+1

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1 | Message
------------ | ------------- | ----------
brad-larson | 1 | +1 

Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/geoengineer&ref=5b8b0dd4fc547543f1d667e8fbafae749b2fb545)

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1 | Message
------------ | ------------- | ----------
brad-larson | 1 | approved 

Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/geoengineer&ref=5b8b0dd4fc547543f1d667e8fbafae749b2fb545)

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1 | Message
------------ | ------------- | ----------
brad-larson | 1 | approved 

Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/geoengineer&ref=5b8b0dd4fc547543f1d667e8fbafae749b2fb545)

**Pull request merged**
