### PR TITLE
Terraform's aws provider doesnt set the kinesis source properly. 

### PR DESCRIPTION
**Pull request by chwevans**
Manually set them.

### CODE REVIEW

**Comment by heimdall-asguard** [comment]
Reviews      | 0/1 | Message
------------ | ------------- | ----------




[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/geoengineer&ref=c35e3166c94e61c6c2d05da275a6398099d6a82d)

**Comment by grahamjenson** [comment]
+1

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1 | Message
------------ | ------------- | ----------
grahamjenson | 1 | +1 

Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/geoengineer&ref=c35e3166c94e61c6c2d05da275a6398099d6a82d)

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1 | Message
------------ | ------------- | ----------
grahamjenson | 1 | +1 

Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/geoengineer&ref=ced6fb3b12bce506b5fc1a992c5e473ef8c8e280)

**Pull request merged**
